# Generated by Django 3.0 on 2021-01-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_to', models.CharField(default='', max_length=200)),
                ('duration', models.CharField(default='', max_length=200)),
                ('price', models.CharField(default='', max_length=100)),
                ('from_s', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
