# Generated by Django 3.0 on 2021-01-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_destinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='destinations_image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
