# Generated by Django 3.0 on 2021-01-30 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210130_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourist',
            old_name='name',
            new_name='fname',
        ),
    ]
